import type { Metadata } from "next";
import { Zen_Kaku_Gothic_Antique, Viga } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import { ColorModeProvider } from "@/context/ColorModeProvider";
import { LockedColorsProvider } from "@/context/LockedColorsContext";
import DataFetchProvider from "@/providers/DataFetchProvider";

const ZenKakuGothicAntiqueFont = Zen_Kaku_Gothic_Antique({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-ZenKakuGothicAntique",
  display: "swap",
});

const VigaFont = Viga({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-Viga",
  display: "swap",
});

export const metadata: Metadata = {
  title: "PaletteMate",
  description: "Generated by create next app",
};

const RootLayout = ({
  params,
  children,
}: Readonly<{
  params: Promise<{ count: string }>;
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ja">
      <body
        className={`${ZenKakuGothicAntiqueFont.variable} ${VigaFont.variable} bg-white text-black antialiased`}
      >
        <HeroUIProvider>
          <DataFetchProvider params={params}>
            <ColorModeProvider>
              <LockedColorsProvider>{children}</LockedColorsProvider>
            </ColorModeProvider>
          </DataFetchProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
};
export default RootLayout;
